# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Horizonte Andalucía
email: horizonteandalucia@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Somos profesoras y profesores de distintas facultades y escuelas de la Universidad de Sevilla, profesionales, estudiantes y en general personas con experiencia en la participación social preocupados por la prolongada situación de estancamiento que vive Andalucía. Nuestra tierra tiene graves carencias sociales, económicas y políticas que es necesario abordar con rigor y honestidad. Creemos que con un pie en la Universidad tenemos adquirida una responsabilidad con la sociedad, de la que formamos parte, y a la que nos debemos.
baseurl: "/" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "http://horizonteandalucia.org/" # change this to the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Make sure to exclude 'vendor' from the build
exclude: [vendor, "Gemfile", "Gemfile.lock"]

# permalink: /:categories/:year/:month/:day/:title.html
# none is equivalent to /:title.html
# https://jekyllrb.com/docs/permalinks
permalink: /:title.html

google_analytics:

# jekyll-theme-simple-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
jekyll-theme-simple-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

show_post_image_posts_list: false

header:
  image: /assets/patterns/symphony.png

# social
author:
  name: "Simple Blog Theme"
  short_bio:
    es: Jekyll Blog Theme, Responsive, SEO and Facebook enabled
  picture: assets/img/profile-60.png

image: /assets/img/profile-225.png

#twitter:
#  username:
#instagram_username:

#linkedin_username: lorepirri

#  site:
facebook:
  publisher_id: 1474191545979552
  profile_id: 1474191545979552
  app_id: 126080721296732
  authors: [1474191545979552]
  #pixelcode: 1670622619859349


# gitlab on site
gitlab:
  owner_url: https://gitlab.com/lorepirri

# github on site
github:
  owner_url: https://github.com/lorepirri


# translation

t:
  es:
    latest-posts:  "Últimos eventos"
    read-more:  "continuar leyendo"
    on-word: "on"
    contact: "Contacto"
    contact-page: "contact.md"
    read-time: "min read"
    comments: "comentar"
    go-to-home-page: "Volver a la pagina de inicio"
    months:
      january: "Enero"
      february: "Febrero"
      march: "Marzo"
      april: "Abril"
      may: "Mayo"
      june: "Junio"
      july: "Julio"
      august: "Agosto"
      september: "Septiembre"
      october: "Octubre"
      november: "Noviembre"
      december : "Diciembre"
 
defaults:
  -
    scope:
      type: "posts"
    values:
      lang: "es"
      category: articles
